version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: edric
      POSTGRES_PASSWORD: edric
      POSTGRES_DB: learnnestjs1
    ports:
      - 5432:5432
  app:
    build: .
    ports:
      - 3002:3002
    depends_on:
      - db
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: edric
      POSTGRES_PASSWORD: edric
